// vite plugin to export exported-methods from 'src/backend/services/app.ts' to 'shared/apiMethods.ts'

import fs from 'fs';
import { resolve } from 'path';
import type { PluginOption } from 'vite';

const electronApiMethods: PluginOption = {
    name: 'export-api-methods',
    buildStart() {
        const rpcServicePath = resolve(__dirname, 'src/electron/rpc.ts');
        const apiMethodsPath = resolve(__dirname, 'src/shared/apiMethods.ts');

        const fileContent = fs.readFileSync(rpcServicePath, 'utf-8') as string;
        const regex = /[\s]*([A-z0-9]+): (_map|async[\s\n]*\(([\s\n]*.*: Ctx|\)))/gm;
        const exportedMethods = [...fileContent.matchAll(regex)].map((match) => match[1]).filter((name) => name !== 'request');

        const names = exportedMethods.map((name) => `'${name}'`).join(',\n    ');
        let content = '// This file is auto-generated by vite-export-api-methods.ts';
        content += `\nexport const apiMethods = [\n    ${names}\n] as const;\n`;

        fs.writeFileSync(apiMethodsPath, content);
    },
};

export default electronApiMethods;
